### ISSUE TITLE
@conda-forge-admin, please update for conda-build 3

### ISSUE THREAD

**Issue by bgruening** [conda-forge/r-lsmeans-feedstock#2]

**Comment by jdblischak** [comment]
Hmm...This doesn't seem to have worked. Maybe it can't be in the title.

**Comment by jdblischak** [comment]
@conda-forge-admin, please update for conda-build 3

**Comment by jdblischak** [comment]
xref: https://github.com/conda-forge/r-rsm-feedstock/pull/2

**Comment by jakirkham** [comment]
This can be closed, right?
